package main

var CarBrands = map[string]bool{
	"Acura":         true,
	"Aixam":         true,
	"Alfa Romeo":    true,
	"Alpina":        true,
	"Alpine":        true,
	"Aston Martin":  true,
	"Audi":          true,
	"BAW":           true,
	"BAIC":          true,
	"Bentley":       true,
	"BMW":           true,
	"Bugatti":       true,
	"Buick":         true,
	"BYD":           true,
	"Cadillac":      true,
	"Changan":       true,
	"Chery":         true,
	"Chevrolet":     true,
	"Citroën":       true,
	"Dacia":         true,
	"Daihatsu":      true,
	"Dodge":         true,
	"DS":            true,
	"Elfin":         true,
	"FAW":           true,
	"Ferrari":       true,
	"Fiat":          true,
	"Ford":          true,
	"Foton":         true,
	"GAC":           true,
	"Geely":         true,
	"Genesis":       true,
	"Ginetta":       true,
	"GMC":           true,
	"Great Wall":    true,
	"Haval":         true,
	"Hino":          true,
	"Honda":         true,
	"Hongqi":        true,
	"Hyundai":       true,
	"Infiniti":      true,
	"Isuzu":         true,
	"Iveco":         true,
	"Jac":           true,
	"Jaguar":        true,
	"Jeep":          true,
	"Kia":           true,
	"Koenigsegg":    true,
	"Lada":          true,
	"Lamborghini":   true,
	"Lancia":        true,
	"Land Rover":    true,
	"Lexus":         true,
	"Ligier":        true,
	"Lincoln":       true,
	"Lotus":         true,
	"Lucid":         true,
	"Lynk & Co":     true,
	"Mahindra":      true,
	"Maruti Suzuki": true,
	"Maserati":      true,
	"Mazda":         true,
	"McLaren":       true,
	"Mercedes-Benz": true,
	"MG":            true,
	"Mini":          true,
	"Mitsubishi":    true,
	"Mitsuoka":      true,
	"Morgan":        true,
	"Nissan":        true,
	"Opel":          true,
	"Ora":           true,
	"Peugeot":       true,
	"Pininfarina":   true,
	"Polestar":      true,
	"Porsche":       true,
	"Proton":        true,
	"Renault":       true,
	"Rimac":         true,
	"Rolls-Royce":   true,
	"Saab":          true,
	"SEAT":          true,
	"Škoda":         true,
	"Smart":         true,
	"Subaru":        true,
	"Suzuki":        true,
	"Tata":          true,
	"Tesla":         true,
	"Toyota":        true,
	"VinFast":       true,
	"Volkswagen":    true,
	"Volvo":         true,
	"Wiesmann":      true,
	"XPeng":         true,
	"Zotye":         true,
	"Zenvo":         true,
}

var FastFoodBrands = map[string]bool{
    "McDonald's": true,
    "Burger King": true,
    "KFC": true,
    "Subway": true,
    "Starbucks": true,
    "Taco Bell": true,
    "Pizza Hut": true,
    "Domino's": true,
    "Papa John's": true,
    "Wendy's": true,
    "Chick-fil-A": true,
    "Popeyes": true,
    "Panera Bread": true,
    "Chipotle": true,
    "Five Guys": true,
    "Shake Shack": true,
    "In-N-Out Burger": true,
    "Whataburger": true,
    "Culver's": true,
    "Jack in the Box": true,
    "Carl's Jr.": true,
    "Hardee's": true,
    "Arby's": true,
    "Dairy Queen": true,
    "Sonic Drive-In": true,
    "Little Caesars": true,
    "Wingstop": true,
    "Church's Texas Chicken": true,
    "Zaxby's": true,
    "Raising Cane's": true,
    "Jimmy John's": true,
    "Jersey Mike's": true,
    "Firehouse Subs": true,
    "Quiznos": true,
    "Tim Hortons": true,
    "Dunkin'": true,
    "Krispy Kreme": true,
    "Jollibee": true,
    "Pret A Manger": true,
    "Greggs": true,
    "Costa Coffee": true,
    "Nando's": true,
    "Telepizza": true,
    "PizzaExpress": true,
    "Hungry Jack's": true,
    "Red Rooster": true,
    "Oporto": true,
    "Guzman y Gomez": true,
    "Zambrero": true,
    "A&W Restaurants": true,
    "Harvey's": true,
    "Pizza Pizza": true,
    "Mr. Sub": true,
    "Mucho Burrito": true,
    "Pita Pit": true,
    "Leon": true,
    "Wasabi": true,
    "Itsu": true,
    "Haldiram's": true,
    "Cafe Coffee Day": true,
    "Burger Singh": true,
    "Wow! Momo": true,
    "Faasos": true,
    "Al Baik": true,
    "Herfy": true,
    "Kudu": true,
    "MOS Burger": true,
    "Lotteria": true,
    "Yoshinoya": true,
    "Sukiya": true,
    "Coco Ichibanya": true,
    "Marugame Udon": true,
    "Pepper Lunch": true,
    "Dicos": true,
    "Yonghe King": true,
    "Kungfu": true,
    "Wallace": true,
    "TKK Fried Chicken": true,
    "Mang Inasal": true,
    "Chowking": true,
    "Greenwich Pizza": true,
    "Red Ribbon": true,
    "Shakey's Pizza": true,
    "Es Teler 77": true,
    "Baba Rafi": true,
    "HokBen": true,
    "The Pizza Company": true,
    "Chester's": true,
    "Simit Sarayi": true,
    "Quick": true,
    "Nordsee": true,
    "Vapiano": true,
    "BackWerk": true,
    "100 Montaditos": true,
    "Pans & Company": true,
    "Rodilla": true,
    "Spizzico": true,
    "El Pollo Loco": true,
    "Pollo Campero": true,
    "Del Taco": true,
    "Qdoba": true,
    "Moe's Southwest Grill": true,
    "Baja Fresh": true,
    "Rubio's Coastal Grill": true,
    "Blaze Pizza": true,
    "MOD Pizza": true,
    "Pieology": true,
    "PizzaRev": true,
    "CAVA": true,
    "Sweetgreen": true,
    "Saladworks": true,
    "Chopt": true,
    "Sbarro": true,
    "Checkers": true,
    "Rally's": true,
    "Bojangles": true,
    "Captain D's": true,
    "Long John Silver's": true,
    "Marco's Pizza": true,
    "Papa Murphy's": true,
    "WingStreet": true,
    "Slim Chickens": true,
    "Golden Chick": true,
    "Portillo's": true,
    "Wienerschnitzel": true,
    "Freddy's Frozen Custard & Steakburgers": true,
    "Smashburger": true,
    "Steak 'n Shake": true,
    "Auntie Anne's": true,
    "Cinnabon": true,
    "Pretzelmaker": true,
    "Penn Station": true,
    "Togo's": true,
    "Schlotzsky's": true,
    "Zippy's": true,
    "L&L Hawaiian Barbecue": true,
    "Teriyaki Madness": true,
    "Bonchon": true,
    "KyoChon": true,
    "Paris Baguette": true,
    "Tous Les Jours": true,
    "Eggslut": true,
    "BIBIBOP Asian Grill": true,
    "Pokeworks": true,
    "Panda Express": true,
    "Pei Wei": true,
    "Taco John's": true,
    "Taco Time": true,
    "Blimpie": true,
    "Charleys Philly Steaks": true,
    "The Halal Guys": true,
    "Torchy's Tacos": true,
    "Velvet Taco": true,
    "Habit Burger Grill": true,
    "Farmer Boys": true,
    "Cook Out": true,
    "Cousins Subs": true,
    "Earl of Sandwich": true,
    "Potbelly": true,
    "Which Wich": true,
    "Zoe's Kitchen": true,
    "Nékter Juice Bar": true,
    "Jamba": true,
    "Smoothie King": true,
    "Cold Stone Creamery": true,
    "Baskin-Robbins": true,
    "Carvel": true,
    "Rita's Italian Ice": true,
    "Yogen Früz": true,
    "Great American Cookies": true,
    "Auntie Lee's": true, // placeholder small chain name; feel free to remove if undesired
    "Crumbl Cookies": true,
    "Insomnia Cookies": true,
    "Tropical Smoothie Cafe": true,
    "PDQ": true,
    "Pollo Tropical": true,
    "Biscuitville": true,
    "CookHouse": true, // placeholder; remove if you only want well-known brands
    "Hungry Howie's": true,
    "Jet's Pizza": true,
    "Mountain Mike's Pizza": true,
    "Godfather's Pizza": true,
    "Round Table Pizza": true,
    "Papa Gino's": true,
    "Hungry Horse": true, // UK pub/quick-service hybrid; optional
    "BGR The Burger Joint": true,
    "Fuddruckers": true,
    "Krystal": true,
    "White Castle": true,
    "Cook Out Fresh Burgers": true, // alt naming; optional
}

var topics = map[string]map[string]bool {
	"car brands": CarBrands,
	"fastfood companies" : FastFoodBrands,
}