// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PartyPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Header content --><header class=\"flex items-center justify-between p-4 shadow-lg\"><div class=\"w-1/4\"></div><div class=\"w-2/4 text-center\"><h1 class=\"font-sans text-4xl\">Word Association</h1></div><div class=\"w-1/4 flex justify-center\"><button class=\"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800\">How to Play</button></div></header><main class=\"flex flex-grow justify-center items-center\"><!-- Party players card --><div class=\"flex flex-col bg-white p-6 rounded-2xl shadow-2xl w-full max-w-sm text-center border border-indigo-100\"><h2>Players</h2><div class=\"flex flex-col\"><div class=\"profile-card-contents flex justify-between\"><img class=\"h-8 rounded-full\" src=\"https://img.freepik.com/free-vector/smiling-young-man-illustration_1308-174669.jpg?semt=ais_hybrid&w=740&q=80\"><p class=\"w-2/4 text-left\">DunkedOnDog</p><div id=\"gameStatus\" class=\" w-1/4 inline-block px-4 py-1 rounded-full font-bold text-sm uppercase transition-all duration-300 shadow-md bg-green-500 text-white mb-6\">Ready</div></div></div><div><button class=\"m-1 p-1 text-center text-violet-600 border border-green-400 rounded hover:bg-green-400 hover:text-white active:bg-green-400 focus:outline-none focus:ring\">Ready</button> <button class=\"m-1 p-1 text-center text-violet-600 border border-red-600 rounded hover:bg-red-600 hover:text-white active:bg-red-600 focus:outline-none focus:ring\">Leave</button></div></div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
